### ISSUE TITLE
linter does not run or perhaps instructions incomplete

### ISSUE THREAD

**Issue by etaiklein** [tlahmann/vscode-alex#2]
Issue:
linter does not run or perhaps instructions incomplete

Instructions to replicate:
1. Install via command palette
2. enable alexLinter
3. restart VSCode
4. type in .txt file
5. Nothing added to 'Problems' section on type or save

**Comment by tlahmann** [comment]
Hey @etaiklein.
Somehow i missed your issue. I have just finished the quick-fix feature and simultaneously revised the settings within the extension. Could you check if this issue still persists with the newest version (0.6.1)? 
Thank you!

**Comment by etaiklein** [comment]
Hey, thanks for fixing it- it seems to work well now.
